root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./bin/glink"
# cmd = "go build -o ./bin/glink ."
cmd = "make build-dev"
delay = 2000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "testarea"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "make build install"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "1s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = true
